### PR TITLE
Update LICENSE

### PR DESCRIPTION
**Pull request by joshgoebel**
Is URL required?  This causes GitHub's license matching to fail...

### CODE REVIEW

**Comment by joshgoebel** [comment]
It's funny because the certainty threshold is 98% match and your just short of that:

97.32620320855615

:-(

**Comment by tajmone** [comment]
> Is URL required? This causes GitHub's license matching to fail...

Well, yes. Adding a back-link makes sense, especially in view of derivative works.

> It's funny because the certainty threshold is 98% match and your just short of that:

Then the problem is GitHub matching algorithm, after all the MIT license demands that for derivative works the author add his/her own copyright notice _above_ the notice of the original author(s), so it's not unusual to find three or four notices stacked on top of each other.

**Comment by joshgoebel** [comment]
> Then the problem is GitHub matching algorithm, after all the MIT license demands that for derivative works the author add his/her own copyright notice above the notice of the original author(s), so it's not unusual to find three or four notices stacked on top of each other.

I think it actually handles that with REGEX... It knows what the copyright line looks like so it wouldn't mind multiple lines... It just doesn't like random URLs. :-)

> Well, yes. Adding a back-link makes sense, especially in view of derivative works.

I guess you're imagining the derivative work copies the license outright then or something?  I was trying to imagine a case where the license file gets separated from the project and where the URL would actually be of any benefit at all... I wonder how some larger projects deal with this?

I get your point, but yet I don't really see anyone else doing this. :-)

Now you've got me curious though... LOL.

**Comment by joshgoebel** [comment]
Ok, it can't make heads or tails of the Arduboy2 license: https://github.com/MLXXXp/Arduboy2

But that's a little more understandable since it's crazy. :-)

Your following the template exactly except for the URL you added.

**Comment by tajmone** [comment]
The MIT License allow discretionary freedom for the copyright notice — besides providing guidelines to add at least your full name and copyright years, and possibly your email, it doesn't impose any standard way of writing the notice. 

> I think it actually handles that with REGEX... It knows what the copyright line looks like so it 
> wouldn't mind multiple lines..

It would have been simpler to just keep parsing until the expected license text is found, instead of speculating on how the notice should look like.

I did stumble upon some rather articulate notices from time to time.

When I create derivative works, I always add a derivative notice too, with a back link, right before the original copyright notice. I think it makes sense to ensure that end user are able to actually find the original project that was used.

**Comment by joshgoebel** [comment]
> It would have been simpler to just keep parsing until the expected license text is found, instead of speculating on how the notice should look like.

It looks for a few regex and then it looks at the word list... so it's not dependent upon layout or spacing... but I assume (I quickly skimmed the source) it's splitting your URL into chunks of:

- https
- github
- com
- highlightjs
- highlightjs-alan

And those 5-6 additional words constitute more than a 2% change to the license text, so it puts you in the 'other' category (to be safe).  

I can see why Github would want the threshold high for stuff like this.  It's not really much harm to not automagically know your exact license... 

You can close this if you want, I was just trying to get the index page of the organization to show the licenses on all the 3rd party languages. :-)

**Comment by tajmone** [comment]
>  I was just trying to get the index page of the organization to show the licenses on all the 3rd party languages.

Then maybe we should use directly SPDX standards and tools (which is what GitHub relies on anyway):

https://spdx.org/

if I remember correctly, it allows adding some machine readable license specifications, which are safer to rely on then RegExs.

**Comment by joshgoebel** [comment]
It's not really what "we" use, it's what GitHub uses. :-)  They use https://github.com/licensee/licensee which purposely looks for license text, not any type of metadata. (and they explain their reason for doing so - or maybe the library does, I forget). 

https://help.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository#detecting-a-license

**Comment by tajmone** [comment]
GitHub uses SPDX for choosealicense.

For projects like this SPDX is better because it can rely on a one-liner comment.

from https://spdx.org/ids :

> ### How do SPDX IDs work?
> 
> In each file in your project, just add a single line in the following format, tailored to your license(s) and the comment style for that file's language:
> 
> 
> ```
> // SPDX-License-Identifier: MIT
> /* SPDX-License-Identifier: MIT OR Apache-2.0 */
> # SPDX-License-Identifier: GPL-2.0-or-later
> ```
> 
> _Read more about [how to use SPDX identifiers](https://spdx.org/ids-how)_

**Comment by joshgoebel** [comment]
Each file sounds kinda annoying. :)

**Comment by tajmone** [comment]
> Each file sounds kinda annoying. :)

Indeed, but we might apply this to a single common file to all packages.

Isn't there room for a JSON info file to go with each third party language? This would allow the license type to specified there, and of course the full text is available in the source.

**Comment by tajmone** [comment]
The really annoying issue at hand is that this approach will ultimately lead many users bending the Rule of Law to please an algorithm — license are contracts, and they shouldn't be limited in such ways. I'm against all automation of legal matters.

Also, I find it rather amusing that I can't put an URL longer than so many chars whereas the End Users Agreement that I had to read and sign to create an account took me about an hour of reading. The point is that in legal matters everyone tries to cover his/her back. So I like to take the safe side and add links to third party assets I reuse for derivative works, and it seems natural to me to add a link to my own works with that in mind.

**Comment by joshgoebel** [comment]
> Isn't there room for a JSON info file to go with each third party language? This would allow the license type to specified there, and of course the full text is available in the source.

Sure, if it was needed for something... a lot of people just use package.json for extra data as well (if the source is an npm package also).

But that wouldn't solve my original issue of GitHub knowing what the license is. :-)  Highlight.js itself doesn't care about the licenses...

**Pull request closed without merging**
